{% set version = '0.2.4' %}

package:
  name: r-xcmswrapper
  version: {{ version|replace("-", "_") }}

source:
  path: /home/tnl495/XCMSwrapper



build:
  number: 0
  skip: True # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - 'r-base >=3.4.1'
    - 'bioconductor-mspurity >=1.4.1'
    - 'bioconductor-mzr >=1.1.6'
    - bioconductor-xcms
    - bioconductor-camera
    - r-rcolorbrewer
    - r-intervals
    - r-nnet
    - r-testthat
    - r-roxygen2
    - bioconductor-faahKO


  run:
    - 'r-base >=3.4.1'
    - 'bioconductor-mspurity >=1.4.1'
    - 'bioconductor-mzr >=1.1.6'
    - bioconductor-xcms
    - bioconductor-camera
    - r-rcolorbrewer
    - r-intervals
    - r-nnet
    - r-roxygen2
    - bioconductor-faahKO




test:
  commands:
    - '$R -e "library(''XCMSwrapper'')"'
about:
  home: https://github.com/computational-metabolomics/xcmswrapper
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'Various tools for LC-MS data processing'
