{% set version = '0.0.8' %}

package:
  name: deconrank
  version: {{ version|replace("-", "_") }}

source:
  git_url: https://github.com/computational-metabolomics/deconrank.git


requirements:
  build:
    - python
    - pip
    - setuptools
    - numpy

  run:
    - python
    - setuptools
    - numpy

test:
  # Python imports
  imports:
    - deconrank

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - python -m deconrank -h

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.github.com/computational-metabolomics/deconrank
  license: MIT License
  summary: 'Rank precursors from a LC-MS or DI-MS experiment for a later fragmentation run'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
