categories: ["Metabolomics"]
description: decon rank
name: deconrank
owner: tomnl
description: Deconvolute adducts and isotopes then score and rank for fragmentation (beta version of galaxy tool)
homepage_url: https://github.com/computational-metabolomics/dma-tools-galaxy
long_description: Deconvolute adducts and isotopes then score and rank for fragmentation (beta version of galaxy tool)
remote_repository_url: https://github.com/computational-metabolomics/dma-tools-galaxy
type: unrestricted
include:
  - deconrank.xml
  - test-data/**
