{% set version = '0.2.3' %}

package:
  name: r-cameradims
  version: {{ version|replace("-", "_") }}

source:
  git_rev: HEAD
  git_url: https://github.com/computational-metabolomics/cameraDIMS.git

build:
  number: 0
  skip: True # [osx]


requirements:
  build:
    - r-base
    - bioconductor-biobase
    - bioconductor-graph
    - r-hmisc
    - r-igraph

  run:
    - r-base
    - bioconductor-biobase
    - bioconductor-graph
    - r-hmisc
    - r-igraph


test:
  commands:
    - '$R -e "library(''cameraDIMS'')"'
about:
  home: https://github.com/computational-metabolomics/cameraDIMS
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'Modification of R CAMERA package to work with DIMS peaklists'
