{% set version = '0.2.7' %}

package:
  name: r-cameradims
  version: {{ version|replace("-", "_") }}

source:
  path: /home/tnl495/code/cameraDIMS



build:
  number: 0
  skip: True # [osx]
  rpaths:
    - lib/R/lib/
    - lib/



requirements:
  build:
    - r-base
    - bioconductor-biobase
    - bioconductor-graph
    - r-hmisc
    - r-igraph
    - r-optparse

  run:
    - r-base
    - bioconductor-biobase
    - bioconductor-graph
    - r-hmisc
    - r-igraph
    - r-optparse


test:
  commands:
    - '$R -e "library(''cameraDIMS'')"'
about:
  home: https://github.com/computational-metabolomics/cameraDIMS
  license: 'GPL (>= 2) + file LICENSE'
  summary: 'Modification of R CAMERA package to work with DIMS peaklists'
